stages:
  prepere:
    cmd: python 1.ipynb
    deps:
    - .\datasets\space_tit_test.csv
    - .\datasets\space_tit_train.csv
    - config.yml
  feature_eng:
    cmd: python 2.ipynb
    deps:
    - .\data\prep
    - .\data\prep\data_test_cleaned.csv
    - .\data\prep\data_train_cleaned.csv
  model:
    cmd: python 3.ipynb
    deps:
    - .\data\clean
    - .\data\clean\data_test_prepared.csv
    - .\data\clean\data_train_prepared.csv
  
  
plots:
  - images/boxes.png