stages:
  prepare:
    cmd: python 1.py data/prep
    deps:
    - 1.ipynb
    - datasets/space_tit_test.csv
    - datasets/space_tit_train.csv
    params:
    - prepare.scale
    outs:
    - data/prep
  featurize:
    cmd: python 2.py data/clean images
    deps:
    - 2.py
    - data/prep
    outs:
    - data/clean
    - images
  train:
    cmd: python 3.py data/out models/model.pkl
    deps:
    - data/clean
    params:
    - train.learning_rate
    outs:
    - data/out
    - models/model.pkl
